name: SuperSpleef
author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
main: com.spleefleague.superspleef.SuperSpleef
version: 1.0
depend: [SpleefLeagueCore, Commands, GameAPI]
loadbefore: [SuperJump]
commands:    
    spleef:
        description: SuperSpleef queue command
        aliases: [s]
        usage: |
          /<command> [arena]
    powerspleef:
        description: SuperSpleef queue command
        aliases: [ps]
        usage: |
          /<command> [arena]
    teamspleef:
        description: TeamSpleef queue command
        aliases: [ts]
        usage: |
          /<command> [arena]
    multispleef:
        description: MultiSpleef queue command
        aliases: [ms]
        usage: |
          /<command> [arena]
    reset:
        description: Resets the current spleef field
        usage:
            /<command> [player]
    playto:
        description: Changes amount of wins needed to be reached to completely win the game
        usage:
            /<command> [wins]
    shovel:
        description: Create, add or remove shovels
        usage:
            /<command> <create|add|remove|reload> [target] [shovelId]